services:
  mysql:
    image: mysql:8.4
    container_name: hris-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hris
      MYSQL_USER: hris
      MYSQL_PASSWORD: hris
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - hris_mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: hris-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  hris_mysql_data: